[[redirects]]
from = '/api/**'
to = 'api-link/:splat'
status = 200
headers = { Access-Control-Allow-Origin = '*', Authorization = 'Bearer api-key'}

[[headers]]
for = '/*'
[headers.values]
Access-Control-Allow-Origin = '**'
Authorization = 'Bearer api-key'

[[headers]]
for = '/api/*'
[headers.values]
Access-Control-Allow-Origin = '**'
Authorization = 'Bearer api-key'