[[redirects]]
from = '/api/**'
to = 'https://twofifteen.co.uk/api/:splat'
status = 200
headers = { Access-Control-Allow-Origin = '*'}

[[headers]]
for = '/*'
[headers.values]
Access-Control-Allow-Origin = '**'

[[headers]]
for = '/api/*'
[headers.values]
Access-Control-Allow-Origin = '**'