[[redirects]]
from = “/api/**”
to = “api-link/:splat”
status = 200
headers = { Access-Control-Allow-Origin = “*”, Authorization = “Bearer api-key”}

[[headers]]
Define which paths this specific [[headers]] block will cover.
for = “/*”
[headers.values]
Access-Control-Allow-Origin = “**”
Authorization = “Bearer api-key”

[[headers]]
Define which paths this specific [[headers]] block will cover.
for = “/api/*”
[headers.values]
Access-Control-Allow-Origin = “**”
Authorization = “Bearer api-key”